### ISSUE TITLE
Text is positioned on bottom edge of bounding box, not on baseline

### ISSUE THREAD

**Issue by bergey** [diagrams/diagrams-rasterific#21]
When `Text` alignment is `BaselineText`, the local origin, from Diagrams' point of view, is on the baseline.  In the `Renderable` instance for `Text`, `refY` should be the vertical distance from the top of the string to the baseline, not the height of the bounding box.  (At least, I think Rasterific & FontyFruity place the origin & axes that way.)

This was reported in https://github.com/timbod7/haskell-chart/issues/65 which has some supporting images.

The `Cairo` Backend is pretty similar to `Rasterific` in this area.  Pango provides a function to locate the baseline; I'm not sure if `FontyFruity` does yet.  SVG is quite different.

**Comment by mmaz** [comment]
Hi, I noticed a kerning discrepancy in the `diagrams-rasterific` backend. Is it possibly due to this issue, or something upstream? I have tried to create a minimal example for reproducing the issue, but I wouldn't be surprised if the difference I'm seeing is platform-specific. I'm on OSX, and I have locally installed the truetype font [Lato](https://github.com/google/fonts/blob/master/ofl/lato/Lato-Regular.ttf) from Google's webfonts repo. When I run the following script with `stack example-svg.hs` :

```haskell
#!/usr/bin/env stack
-- stack --resolver lts-3.5 --install-ghc runghc --package diagrams
{-# LANGUAGE NoMonomorphismRestriction #-}
import Diagrams.Prelude
import Diagrams.Backend.SVG

d :: Diagram B
d = text "QRSTUVqrstuv" # font "Lato" <> rect 10 2 # fc white

main = renderSVG "test.svg" (mkWidth 400) d
```
in the SVG output, the uppercase `T` and lowercase `t` "correctly" butt against `U/u` (as seen on the left side of the example screenshot included below - I am assuming that Safari is relying on OSX's kerning support for this)

However, the following, after running with `stack example-rasterific.hs`,
```haskell
#!/usr/bin/env stack
-- stack --resolver lts-3.5 --install-ghc runghc --package diagrams --package diagrams-rasterific
{-# LANGUAGE NoMonomorphismRestriction #-}
import Diagrams.Prelude
import Diagrams.Backend.Rasterific

d :: Diagram B
d = text "QRSTUVqrstuv" # font "Lato" <> rect 10 2 # fc white

main = renderRasterific "test.png" (mkWidth 400) d
```

contains "incorrect" kerning for `TU` and `tu` in the output PNG file (on the right in the below screenshot).

![diagrams-svg-left-diagrams-png-right](https://cloud.githubusercontent.com/assets/844789/9969995/2a7805a2-5e20-11e5-8648-d4fc6c59a757.png)

Thoughts? Lastly, please forgive my casual tossing about of 'correct/incorrect' labels above regarding kerning; I fully appreciate how tricky consistent font rendering is (especially across platforms!) and I am eternally grateful to the maintainers, for both `diagrams` and all the wonderful backends! It is an indispensable library to me.

**Comment by jeffreyrosenbluth** [comment]
I don't even think diagrams-rasterific currently has the ability to use fonts that are not internal to the system. I.e.,  ```... font "Lato" <> ...``` does not effect the choice of font, which is open sans in rasterific.
So one thing you might be  noticing is the difference between open sans and Lato. Even so the kerning issue seems to far off for this to explain and my guess is that it's a problem with rasterific/fonty-fruity.

**Comment by bergey** [comment]
It looks like `FontyFruity-0.4.2` exposes the baseline height that we need.  (https://github.com/Twinside/FontyFruity/commit/de4d69f4213c388f01959b19da52442d731c7016) This should be fairly straightforward now.
